FROM rayproject/ray:2.57.0

# Install dependencies needed for training and registry logging
RUN pip install --no-cache-dir \
    mlflow==3.15.1 \
    scikit-learn \
    pandas \
    boto3 \
    cryptography \
    psycopg2-binary \
    lakefs==0.16.0 \
    lakefs-sdk==1.86.0
