"""create_deployments_and_add_performance_indexes

Revision ID: 710094a7e4a1
Revises: 7ef148a0dad6
Create Date: 2026-09-22 11:19:13.853349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710094a7e4a1'
down_revision: Union[str, Sequence[str], None] = '7ef148a0dad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('rayservice_name', sa.String(length=100), nullable=True),
    sa.Column('endpoint_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_username', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_created_at'), 'deployments', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployments_created_by_id'), 'deployments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_deployments_deployment_id'), 'deployments', ['deployment_id'], unique=True)
    op.create_index(op.f('ix_deployments_model_name'), 'deployments', ['model_name'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_blacklisted_tokens_created_at'), 'blacklisted_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_datasets_created_at'), 'datasets', ['created_at'], unique=False)
    op.create_index(op.f('ix_datasets_created_by_id'), 'datasets', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_created_at'), 'training_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_jobs_created_by_id'), 'training_jobs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_training_jobs_created_by_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_created_at'), table_name='training_jobs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_datasets_created_by_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_created_at'), table_name='datasets')
    op.drop_index(op.f('ix_blacklisted_tokens_created_at'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_model_name'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployment_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_by_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_at'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
