"""create training_jobs table

Revision ID: 7ef148a0dad6
Revises: 46bfc95b5dd9
Create Date: 2026-09-21 09:27:32.230011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef148a0dad6'
down_revision: Union[str, Sequence[str], None] = '46bfc95b5dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('rayjob_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('experiment_name', sa.String(length=100), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('entrypoint', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_by_username', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_job_id'), 'training_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_training_jobs_rayjob_name'), 'training_jobs', ['rayjob_name'], unique=True)
    op.create_index(op.f('ix_training_jobs_status'), 'training_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_jobs_status'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_rayjob_name'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_job_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###
