"""add training_jobs table

Revision ID: bee587bde3b6
Revises: 46bfc95b5dd9
Create Date: 2026-09-21 13:21:38.770892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee587bde3b6'
down_revision: Union[str, Sequence[str], None] = '46bfc95b5dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('job_id', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('experiment_name', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('training_duration', sa.Float(), nullable=True),
    sa.Column('confusion_matrix', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('roc_curve', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_job_id'), 'training_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_jobs_job_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    # ### end Alembic commands ###
